#cloud-config
package_update: false
package_upgrade: false

write_files:
  # =========================
  # MAIN INSTALL SCRIPT (BASE64)
  # =========================
  - path: /root/setup-vm.sh
    permissions: '0755'
    encoding: b64
    content: |
      BASE64_CODE_WORDPRESS-SETUP.SH

  # =========================
  # FIRST LOGIN TRIGGER
  # =========================
  - path: /etc/profile.d/wordpress-first-login.sh
    permissions: '0755'
    content: |
      #!/bin/bash

      # =========================
      # ONLY ROOT + INTERACTIVE
      # =========================
      [ "$USER" != "root" ] && return
      [[ $- != *i* ]] && return

      # =========================
      # PREVENT RE-RUN
      # =========================
      if [ -f /root/.wordpress_installed ]; then
          return
      fi

      clear
      echo "======================================"
      echo "   WORDPRESS FIRST LOGIN INSTALLER"
      echo "======================================"
      echo ""
      echo "[INFO] Menjalankan installer..."
      echo ""

      # =========================
      # RUN INSTALLER
      # =========================
      bash /root/setup-vm.sh
      STATUS=$?

      if [ $STATUS -ne 0 ]; then
          echo "[ERROR] Installer gagal!"
          return
      fi


      # =========================
      # MARK AS DONE
      # =========================
      touch /root/.wordpress_installed

      # =========================
      # SELF DESTRUCT 🔥
      # =========================
      rm -f /etc/profile.d/wordpress-first-login.sh
      rm -f /root/setup-vm.sh

      echo ""
      echo "[INFO] Installation Wordpress finished"
